name: rspec

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  RAILS_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 3.0
          - 3.1
          - 3.2
          - 3.3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rspec
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
